### ISSUE TITLE
Anaphora resolution and linking in task-1

### ISSUE THREAD

**Issue by jplu** [anuzzolese/oke-challenge#14]
Hi,

I saw that you have added anaphora resolution and linking like:

```
<http://www.ontologydesignpatterns.org/data/oke-challenge/task-1/sentence-18#char=71,73>
        a                     nif:String , nif:RFC5147String ;
        nif:anchorOf          "he"@en ;
        nif:beginIndex        "71"^^xsd:int ;
        nif:endIndex          "73"^^xsd:int ;
        nif:referenceContext  <http://www.ontologydesignpatterns.org/data/oke-challenge/task-1/sentence-18#char=0,114> ;
        itsrdf:taIdentRef     oke:Lee_Allen_1 .
```

But it is not explicitely indicated in the guidelines. Is-it an error or is-it normal and forgot to be added in the guidelines ?

Cheers.

**Comment by anuzzolese** [comment]
Hi,

in the task description we state that "entities are any discourse referent, either named or anonymous".
Hence, anaphorically related discourse referents are included in the task.

In order to be clearer, I have just added this paragraph in the guidelines:

"Entities also include anaphorically related discourse referents. Hence, anaphora resolution has to be take into account for addressing the task."

Andrea

**Comment by jplu** [comment]
Ok, fair enough. Thank you for the clear answer.
